import ResourceBundleUtil from "@jangaroo/runtime/l10n/ResourceBundleUtil";
import FeedbackHubSearchmetrics_properties from "./FeedbackHubSearchmetrics_properties";

/**
 * Overrides of ResourceBundle "FeedbackHubSearchmetrics" for Locale "de".
 * @see FeedbackHubSearchmetrics_properties#INSTANCE
 */
ResourceBundleUtil.override(FeedbackHubSearchmetrics_properties, {
  searchmetrics_title: "Searchmetrics",
  searchmetrics_ariaLabel: "Searchmetrics",
  searchmetrics_tooltip: "Artikeltext mit Searchmetrics Vorgaben prüfen",
  searchmetrics_button_tooltip: "In Searchmetrics öffnen",
  searchmetrics_briefing: "Briefing",
  searchmetrics_briefing_reload_button: "Briefings neu laden",
  searchmetrics_briefing_title: "Briefing Titel",
  searchmetrics_briefing_no_content: "Der Briefing Text ist leer.",
  searchmetrics_briefing_content: "Searchmetrics Briefing Inhalt",
  searchmetrics_briefing_content_title: "Text in Searchmetrics",
  searchmetrics_briefing_apply_button: "Briefing anwenden",
  searchmetrics_briefing_content_help: "Dies ist der Text der aktuell in Searchmetrics für dieses Briefing gespeichert ist. Bei der Auswahl eines Briefings wird dieser Text mit dem Inhalt des aktuellen Artikels überschrieben.",
  searchmetrics_briefing_emptyText: "Briefing auswählen",
  searchmetrics_briefing_not_selected: "<i>Das ausgewählte Briefing wird hier angezeigt.<\/i>",
  searchmetrics_briefing_title_not_selected: "<i>Der Titel des Briefings wird hier angezeigt.<\/i>",
  searchmetrics_briefing_apply_title: "Briefing anwenden",
  searchmetrics_briefing_apply_text: "Mit der Anwendung des Briefings wird der Text in Searchmetrics überschrieben und kann nicht wiederhergestellt werden.",
  searchmetrics_briefing_loading: "<i style=\"color:#c7c7c7;\">Lade Briefing Text...<\/i>",
  searchmetrics_general_tab_title: "Übersicht",
  searchmetrics_content_tab_title: "Inhalt",
  searchmetrics_keywords_tab_title: "Keywords",
  searchmetrics_questions_tab_title: "Fragen",
  searchmetrics_competitors_tab_title: "Plagiate",
  searchmetrics_content_score: "Content Score",
  searchmetrics_score_details: "Score Details",
  searchmetrics_readability: "Lesbarkeits-Score",
  searchmetrics_selected_briefing: "Ausgewähltes Briefing: {0}",
  searchmetrics_word_count: "Wortzahl",
  searchmetrics_sentence_structure: "Satzstruktur",
  searchmetrics_keyword_coverage: "Keyword Abdeckung",
  searchmetrics_repetitions: "Wiederholungen",
  searchmetrics_main_scores: "Scoring Übersicht",
  searchmetrics_score_easy: "Leicht",
  searchmetrics_score_difficult: "Schwer",
  searchmetrics_must_have_keywords: "Must-Have Keywords",
  searchmetrics_recommended_keywords: "Empfohlene Keywords",
  searchmetrics_additional_keywords: "Zusätzliche Keywords",
  searchmetrics_other_questions: "Andere",
  searchmetrics_other_questions_en: "Other",
  searchmetrics_competitors_duplicate_check: "Plagiate Finder",
  searchmetrics_duplicated_page: "Duplikat",
  searchmetrics_similarity: "Ähnlichkeit",
  searchmetrics_question_list: "Fragen",
  searchmetrics_show_analyzed_pages: "Klicken Sie hier um alle analysierten Seiten in Searchmetrics anzeigen",
  searchmetrics_load_more: "Lade mehr ({0})",
  searchmetrics_questions: "{0} Fragen",
  searchmetrics_other_questions_de: "Andere",
  searchmetrics_loading: "Lade Content Scores...",
  searchmetrics_duplicate_warning: "Im Text wurde/n {0} schwerwiegende/s Plagiat/e gefunden.",
  searchmetrics_duplicate_ok: "Keine Duplikate gefunden. Sehr gut!",
  searchmetrics_qtip_must_have_keywords: "<b>Must-Have Keywords<\/b><br/><br/> Must-Have-Keywords sind von zentraler Bedeutung für das Thema/die Themen, auf das/die Sie abzielen. Diese Begriffe werden im Content Ihrer Mitbewerber häufig verwendet. Es ist für Sie entscheidend, diese Begriffe in Ihren Content einzubeziehen, um eine gute Leistung in den Suchmaschinen zu erzielen.",
  searchmetrics_qtip_recommended_keywords: "<b>Wichtige Keywords<\/b><br/><br/> Wichtige Keywords sind Begriffe, die viele (aber nicht alle) Ihrer Mitbewerber verwenden. Diese Begriffe stehen im Zusammenhang mit Ihrem Thema/Ihren Themen, sind jedoch von nicht so zentraler Bedeutung wie die Must-Have-Keywords. Beziehen Sie wichtige Keywords ein, um den holistischen Content zu erstellen, nach dem Ihre Zielgruppe sucht.",
  searchmetrics_qtip_additional_keywords: "<b>Zusätzliche Keywords<\/b><br/><br/> Zusätzliche Keywords sind nicht von zentraler Bedeutung für das Thema/die Themen, auf das/die Sie abzielen und vielleicht nicht einmal im engsten Sinne relevant. Wenn Sie diese Begriffe jedoch in Ihren Content einbeziehen, kann dies die Einzigartigkeit Ihres Contents erhöhen. Suchmaschinen belohnen Einzigartigkeit. Wenn Sie diese Begriffe einbeziehen, kann dies Ihnen dabei helfen, ein besseres Ranking als Ihre Mitbewerber zu erzielen und in den Augen Ihrer Zielgruppe aus der Menge herauszustechen.",
  searchmetrics_qtip_content_score: "<b>Content Score<\/b><br><br>Der Content Score stellt dar, wie holistisch und umfassend Ihre Inhalte das/die Thema(en) ansprechen. Es basiert auf 4 Komponenten: Wortzahl, Satzstruktur, Schlüsselwortabdeckung und Wiederholungen. Wir wissen, dass guter Text aus allen 4 Faktoren gleichermaßen besteht.<br><br>Je höher der Content Score, desto besser ist die Abdeckung des jeweiligen Themas und desto höher ist das Potential, dass Ihre Inhalte in der Suchmaschine erfolgreich sind.",
  searchmetrics_qtip_word_count: "<b>Wie wird die Wortzahl berechnet?<\/b><br/><br/> Dieser Score stellt die Lücke zwischen der Anzahl der Wörter im Text und der Anzahl der Zielwörter dar. Die Ziel-Wortanzahl wurde vom Ersteller des Briefings festgelegt und basiert in der Regel auf der Wortanzahl der konkurrierenden Seiten. Der Zielwert beeinflusst die empfohlenen Keyword-Frequenzen und beeinflusst den gesamten Content Score.",
  searchmetrics_qtip_sentence_structure: "<b>Was ist Satzstruktur?<\/b><br/><br/> Dieser neue Score bewertet, wie gut Ihr Text strukturiert ist. Mit unserem neuen Deep-Learning-Algorithmus können wir erkennen, wenn Sie keine natürliche Sprache verwenden, und den Score entsprechend berechnen. Z.B. Wenn Sie einen Satz wie \"Ich esses Fisch\" schreiben, können wir feststellen, dass dies nicht die richtige Sprache ist und sich dementsprechend negativ auf Ihren Score auswirkt.",
  searchmetrics_qtip_keyword_coverage: "<b>Verwenden Sie die richtigen Schlüsselwörter?<\/b><br/><br/> Dieser Score berechnet Ihre Keyword-Abdeckung, basierend auf unseren Empfehlungen. Je mehr Schlüsselwörter Sie in Ihren Text einfügen, desto höher ist der Score.",
  searchmetrics_qtip_repetitions: "<b>Wie oft wiederholen Sie Ihren Text?<\/b><br/><br/> Wenn Sie Sätze und Phrasen in Ihrem Text stark wiederholen, wird Ihr Score beeinflusst. Dies gilt nicht für einzelne Wörter, sondern nur für Phrasen & Sätze.",
  searchmetrics_qtip_readability_score: "<b>Lesbarkeits-Score<\/b><br/><br/> Der Lesbarkeits-Score, der von der „Flesch-Kincaid-Lesbarkeit“ abgeleitet ist, soll dabei helfen die Lesbarkeit von Texten zu beurteilen. Der Score basiert auf der Länge der Sätze und der Anzahl von Silben in einem Wort.<br><br>Das Bewertungssystem reicht von 0-10:<ul><li><b>0-3:<\/b> schwieriger zu lesen<\/li><li><b>3-5:<\/b> weniger schwer zu lesen<\/li><li><b>5-7:<\/b> allgemein verständlich<\/li><li><b>7-10:<\/b> leicht zu lesen & zu verstehen<\/li><\/ul>",
  searchmetrics_qtip_duplicates: "<b>Plagiate Finder<\/b><br/><br/>Der Plagiate Finder zeigt auf, ob sich in Ihrem Text Abschnitte befinden, die ebenso auf einer anderen Webseite zu finden sind. Diese Duplikate kommen zustande, wenn bei der Erstellung Ihres Textes fremde Inhalte kopiert oder Ihre Texte von anderen Webseiten dupliziert wurden.<br><br>Der Plagiate Finder analysiert Ihren Text und vergleicht diesen mit den Webseiten, die mit den gleichen Themen bei Google ranken. Anschließend wird die Ähnlichkeit der analysierten Webseiten zu Ihrem Text aufgelistet und in 3 Kategorien unterteilt:<ul><li>Schwerwiegende Duplikate (51-100%): Diese tauchen auf wenn große Teile Ihres Textes offensichtlich von einer der top rankenden Webseiten zu de gleichen Thema kopiert wurden.<\/li><li>Minderschwere Duplikate (16-50%): Diese tauchen auf wenn kleine Textabschitte kopiert wurden.<\/li><li>Keine Duplikate (<16%): Es wurden keine signifikanten Duplikate gefunden.<\/li><\/ul>Plagiatismus erhöht im Allgemeinen die Wahrscheinlichkeit, dass die Performance der Webseite verschlechtert wird. Umso geringer die Ähnlichkeit zu fremden Textinhakten, umso besser.",
  searchmetrics_error_API_KEY_NOT_SET: "Bitte geben Sie einen g�ltigen apiKey in der Konfiguration f�r {0} an.",
  searchmetrics_error_API_SECRET_NOT_SET: "Bitte geben Sie einen g�ltigen sharedKey in der Konfiguration f�r {0} an.",
  searchmetrics_error_PROJECT_ID_NOT_SET: "Bitte geben Sie einen g�ltige projectId in der Konfiguration f�r {0} an.",
  searchmetrics_error_PROPERTY_NOT_SET: "Bitte geben Sie einen g�ltige propertyName in der Konfiguration f�r {0} an.",
});
